### ISSUE TITLE
Not an issue, but rather a big thumbs up for the work you have done

### ISSUE THREAD

**Issue by GSzabados** [zpieslak/mobilus-client#14]
It is a common issue, especially on the Polish market, that people asking about how to integrate COSMO to their home automation system, like Home Assistant. The solutions so far were underwhelming... 

I've just found your work and feel happy for it, that somebody finally did it. I suggested people multiple times to contact the manufacturer and ask for documentation to integrate it, but nobody has really bothered about it. 

I shared your Repo on the HA forum and on another Polish forum as well, so you might have some people who will try it in their HA setup. It is definitely better than soldering relays to a remote control.

Keep up with the good work!

**Comment by zpieslak** [comment]
Hi @GSzabados,

Thank you for the kind words! I also explored alternative (software) solutions like Google Home -> Home Assistant. I didn’t go for soldering, but I know that solution exists as well. As you mentioned, the manufacturer hasn’t provided any (direct) integration with Home Assistant, but at least there’s the COSMO GTW gateway, which exposes a web interface—that’s already a big help.

My ultimate goal is to develop a Home Assistant plugin. However, due to the amount of work required, I decided to split it into two parts: a bare client and a plugin. Since the client is ready, I’ll now focus on the plugin, though perhaps someone else might pick it up and be even faster (which would also be great :) ).

I’ll close the issue to keep the tracker clean, but thanks again—posts like yours are really motivating!
